spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

rest:
  endpoints:
    - http://wiremock1:8080/orders
    - http://wiremock2:8080/audit   # example of a second endpoint

logging:
  level:
    org.apache.camel: INFO

camel:
  springboot:
    main-run-controller: true

incoming:
  queue: INCOMING.ORDERS.NEW
